### PR TITLE
Gh-2745: Fix crown copyright link

### PR DESCRIPTION
**Pull request by AnirbanPatragithub**
Fixed Crown Copyright Link on Line 44

### CODE REVIEW

**Comment by GCHQDeveloper314** [comment]
Hello, thanks for your contribution. I've renamed the PR title to fit the naming scheme we use, this is partly described on our new [ways of working](https://gchq.github.io/gaffer-doc/latest/ways-of-working/#workflow) page.

**Comment by AnirbanPatragithub** [comment]
Is there anything I need to do close this PR?
I am new and will need some assistance.

**Comment by GCHQDeveloper314** [comment]
@AnirbanPatragithub there's nothing more for you to do. We just need to review and then trigger the merging of the PR which will close it.

**Comment by n3101** [comment]
@p3430233 Please can you find a bit of time to review this?

**Review by GCHQDeveloper314 — APPROVED** [review]

**Review by p3430233 — APPROVED** [review]

**Comment by n3101** [comment]
@p3430233 @GCHQDeveloper314 Thanks guys.

**Comment by p3430233** [comment]
@AnirbanPatragithub Thanks for your contribution

**Pull request merged**
