### PR TITLE
gh-2400 update example scripts to use spring boot maven plugin

### PR DESCRIPTION
**Pull request by javadev001001**
Update example scripts to use Maven Spring-Boot plugin

### CODE REVIEW

**Review by GCHQDev404 — CHANGES_REQUESTED** [review]
retracted

**Comment by t92549** [comment]
Having problems testing this as the branch is out of date

**Comment by n3101** [comment]
Leave this until after dependency up versioning which will include Spring.

**Comment by GCHQDeveloper314** [comment]
Was the intention of this to change the demos to run using Spring Boot instead of using Tomcat? In #2608 they have been improved to use Tomcat 9 instead of 7. The demos seem to work ok, what is the benefit of this PR? Can it be closed now?

**Comment by n3101** [comment]
Overtaken by events

**Pull request closed without merging**
