### PR TITLE
gh-2600: Update v2 README and docs links

### LINKED ISSUE #2600: Update Gaffer 2 README
The Gaffer Readme used for alpha 1 still documents gaffer-tools artefacts we have removed in alpha1 - jar-shader, slider & schema-builder. (but not the analytic ui).

### PR DESCRIPTION
**Pull request by t92549**
# Related Issue

- Resolve #2600

### CODE REVIEW

**Comment by t92549** [comment]
I removed semi-colons at the end of bullet points because I thought it looked weird but that's just a stylistic decision that is subjective.

**Review by GCHQDeveloper314 — APPROVED** [review]
I was going to mention the change of capitalisation for the doc and tools links, then I realised this was because those repositories are not capitalised. All looks good to me, I agree with removing the semicolons.

**Comment by t92549** [comment]
@GCHQDeveloper314 There are a lot of links to things like the getting-started docs which still point to v1docs, I think for these links we should just replace them as and when the v2 versions of these docs are added. Sound good to you?

**Comment by GCHQDeveloper314** [comment]
Yes I agree with that. As part of creating the new docs we should review the READMEs with a view to moving the majority of their content over. This will make maintenance easier in future.

**Pull request merged**
