### PR TITLE
gh-879 remove unneccesary line

### PR DESCRIPTION
**Pull request by morrme**
Removed unnecessary line from configuration per issue.

Closes: #879

### CODE REVIEW

**Comment by p013570** [comment]
Hi @morrme,

Thanks for making the change. Before we can merged you pull request in, we will need you to sign our [Contributor-License-Agreement](https://github.com/gchq/Gaffer/wiki/GCHQ-OSS-Contributor-License-Agreement-V1.0). There is a link at the bottom of there to send an email. 

I know it seems silly to have to sign it for a pull request that just involves removing a line of code. But, you just have to sign it once and you will then be able to make contributions to any of GCHQ's OSS projects.

Thanks again.

**Comment by morrme** [comment]
@p013570 I did see that in the requirements and sent you a message asking if there was another link or template of the message. The link there is a` mailto:` and it does not parse well when sending from a webmail client.

**Comment by p013570** [comment]
Ah sorry I missed the email. 

We just need an email containing the following with your full name and GitHub ID:

```
I hereby agree to the terms of GCHQ Open Source Contributor License Agreement V1.0.

Full name:
GitHub ID:
```

**Comment by morrme** [comment]
@p013570 done. :)

**Comment by p013570** [comment]
Thank you very much.

If you would like any help getting started with any of the other issues then please let me know. As you probably noticed we have started to label issues as beginner and intermediate, so picking some of them would probably be best.

As you did, if you want to work on any of the issues just add a comment to the issue and hopefully that will prevent anyone else doing it.

**Pull request merged**
