### PR TITLE
Response to the gh-1836-demo example.

### PR DESCRIPTION
**Pull request by phosphorbronze50**
I have looked at the demo and taken that and other comments and reorganised the approach to the Mock to Mini Accumulo changes.
This pull request branch has only a few changes outlining how I will go about progressing gh-1836.

It was noted for the gh-1836-demo that as the Mini Accumulo Cluster should behave exactly as full Accumulo we shouldn't need any MiniAccumuloStore sub classes. This does indeed work but given the normal mechanism used by Gaffer to identify a store type is the class name specified in the properties files. This means the MiniAccumuloStore and SingleUseMiniAccumuloStore classes are needed for identification purposes, unless I have misunderstood something in this area.
The new MiniAccumuloStore class extends AccumuloStore with no changes to functionality.
The new SingleUseMiniAccumuloStore extends MiniAccumuloStore in exactly the same manner as SingleUseAccumuloStore extends AccumuloStore.
They are extended in this way rather than SingleUseMiniAccumuloStore extending SingleUseAccumuloStore to replicate the AccumuloStore object hierarchy.

Control of the decision whether to start a MiniAccumuloCluster, and the starting and stopping it, is handled by the new AccumuloTestClusterManager class. This takes an AccumuloProperties object in its constructor and reads it to find the store class. If it is a Mini Accumulo one it sets up and starts a MiniAccumuloCluster and updates the properties with the zookeeper details. If not it just returns.
Creation of the object is called at the beginning of a test suite, often through the @BeforeClass annotated method.
At the end of a test suite (@AfterClass) the close method is called to close and tidy away the Mini Accumulo Cluster if one has been started. The test suite will have kept the reference to the AccumuloTestClusterManager object for this purpose.

There are three tests converted from using Mock to Mini:
AccumuloStoreITs from the demo is suitably modified to use the new AccumuloTestClusterManager. This is slightly odd looking as for this test the constructors receive the properties. This prevents use of the @BeforeClass as that has to be a static method so cannot use instance attributes.
GetDataFrameOfElementsHandlerTest is a spark-accumulo test that was constructed to set up its store only from properties. This was among the tests that previously had a lot of duplicated code. They will now have an abstract superclass, AbstractPropertiesDrivenTest, to handle most of the repeating setup.
AccumuloStoreTest is an example of the most common types of unit tests. This had explicit Mock handling as part of the tests, in some cases with SingleUseMockAccumuloStore being instantiated by individual tests. This has been converted to reuse of a pair of mini accumulo clusters for all the tests.

In all the test examples above I have avoided declaration of the MiniAccumuloStore and SingleUseMiniAccumuloStore classes as far as possible, instead having any necessary Store declarations being for AccumuloStore.

Is this closer to what was expected?

### CODE REVIEW

**Comment by d47853** [comment]
Thanks @phosphorbronze50. That sounds a lot more in-tune with my thinking at least. Have you made these changes in your other pull request? And if so is it ready for a second review?

**Comment by phosphorbronze50** [comment]
Because of the nature of the changes and the need to revisit everything in the last pull request branch I am going to abandon the previous one and move ahead with this one, bringing the changes from the other through to this one as required.

**Comment by d47853** [comment]
Seems sensible. Do you mind if I close both pull requests so you can re-open this one when you're ready for it to be reviewed?

**Comment by phosphorbronze50** [comment]
Closing both pull requests is fine with me.

**Pull request closed without merging**
