### PR TITLE
gh-113 - added advanced mode

### PR DESCRIPTION
**Pull request by p013570**
By default Stores will register all operations. When advanced mode is disabled, the advanced operations (e.g. AddElementsFromHdfs) are not registered. This means when a Graph is instantiated for use via the rest api, advanced mode can be disabled and the advanced operations are then not available via the rest api.

I'm not completely convinced with the "advanced mode" idea. Perhaps it needs a different name. What do you think?

### CODE REVIEW

**Comment by gaffer01** [comment]
Not sure. Maybe the general pattern is that a store can have an optional list of enabled operations in its properties? So admins can instantiate a store with all options enabled, but the store that is used in a REST API will only have a small number of operations enabled?

**Comment by p013570** [comment]
@gaffer01 perhaps yeah. I'm not quite sure how that would look though.

Currently admins can enable/disable any operations by providing an operations declarations file when the store is initialised. This feature is hidden away a bit but it is possible.

**Comment by gaffer01** [comment]
If we can already provide similar functionality with the declarations file, then I don't think "advanced" makes sense. The only option I can think of is a "don't enable additional operations" option. If this is on, then you only get to use the default operations that all stores provide.

**Comment by gaffer01** [comment]
Another thought: is there any value in having a "read-only" mode? If this is on then you can't run any operation that changes the graph.

**Comment by p013570** [comment]
I think there are some operations like AddElementsFromHdfs, AddElementsFromRdd, GetRddOfElements etc. that should not be executed over the rest api. It would be nice if there was a way the core rest api could disable these operations rather than every admin having to write their own operation declaration file to disable them.

**Comment by p013570** [comment]
OK I'll try using the operation declarations to disable them. I'll close this pull request for now.

**Pull request closed without merging**
