### PR TITLE
gh-1865 - Regex and BiPredicate filtering

### PR DESCRIPTION
**Pull request by nikmanG**
In reference to #1865 allows for both regex filtering and bipredicate.

### CODE REVIEW

**Comment by d21211122** [comment]
Hi,

Thanks for your contribution - the functions look really useful.

We don’t usually add functionality like this directly to our value objects, though, rather we add that logic to external functions. You can see an example of that if you look at the FreqMapAggregator in the functions package. So rather than adding an ‘aggregate’ method to the FreqMap, we’ve created an external function that accepts 2 FreqMaps and merges them together.

Similarly, we’d prefer to create an external FreqMapFilter function, that takes a Predicate as an argument that is used to filter the keys. The Koryphe project already has a Regex matching predicate that you could re-use for adding the regex functionality.

I guess it’d look a little like this:

class FreqMapFilter extends KorypheFunction<FreqMap, FreqMap>
{
    private Predicate<String> keyFilter;

    public FreqMapFilter() {}

    public FreqMapFilter(Predicate<String> p)
    {
        keyFilter = p;
    }

    public FreqMap apply(FreqMap input)
    {
        //iterate through the entries in input FreqMap and remove if keyFilter predicate test fails
    }
}

You can then use the Koryphe Regex predicate to get the specific functionality you want:

FreqMapFilter fmf = new FreqMapFilter(new Regex(“myPattern”));
FreqMap filtered = fmf.apply(myFreqMap);

**Comment by gaffer01** [comment]
@d21211122 Should #1865 be updated then to say what the correct approach is? It implies that a Regex predicate is needed but as you say that already exists in Koryphe. So we just need a FreqMapKeyFilter class which accepts a predicate.

**Comment by d47853** [comment]
Could you change the base from master to develop?

**Comment by nikmanG** [comment]
All done but had trouble serializing because of the predicate.

**Comment by nikmanG** [comment]
Given that the JSONSerialiser needs an empty constructor I think the best course of action would be to change it to return the original freq map (a copy of it anyway). That's two birds with one stone.
The issue I had with serializing the predicate is that it will return
`predicate = {}` even when provided a method hence making that somewhat a lost cause.

**Comment by d47853** [comment]
I guess this ties back to @d21211122's suggestion of using Koryphe predicates which would give you the ability to serialise it.

**Pull request merged**
