### PR TITLE
Gh 821 849 new operations

### PR DESCRIPTION
**Pull request by t616178**

### CODE REVIEW

**Comment by t616178** [comment]
Closing to make some fixes/updates

**Comment by t616178** [comment]
Reopening to re-run travis-ci and codecov.

**Comment by t616178** [comment]
Closing to update tests

**Comment by t616178** [comment]
Reopened after updates.

**Comment by p013570** [comment]
Replaced with pull request: https://github.com/gchq/Gaffer/pull/900

**Pull request closed without merging**
