### PR TITLE
Gh 880 split points

### PR DESCRIPTION
**Pull request by p013570**

### CODE REVIEW

**Comment by gaffer01** [comment]
Is there any reason to use `Base64` from `net.iharder.base64` rather than `org.apache.commons.codec.binary.Base64` which is what is used in `IngestUtils`?

**Comment by p013570** [comment]
@gaffer01 don't think so, it would make more sense to use the same. I'll make that change now, thanks.

**Comment by p013570** [comment]
@gaffer01 happy with the changes?

**Comment by gaffer01** [comment]
@p013570 Yes, looks good, but CI build is failing.

**Pull request merged**
